### ISSUE TITLE
Persona 3 Portable has Taken Over my Computer

### ISSUE THREAD

**Issue by dnfanjos** [ParthK117/Emuloader#1]
i decided to use the "steam" part of emuloader and downloaded Persona 3 Portable, but it started doing errors with .NET Framework so i started canceling everything out of impulse, now i´m left with a file with the name Shin$Megami$Tensei$-$Persona$3$Portable$Europe.iso, i cannot delete it as it says it needs admin perms and i am the admin, i´ve tried scanning for a virus (all clean) and tried iobit unlocker (finds and deletes processes that lock a file from being moved/deleted) and nothing happened, i´m not so pleased about this experience and i would like to get help deleting this file (btw the .eldr i used was from Freeroms) 
![image](https://user-images.githubusercontent.com/25671367/85946694-26e6eb00-b93e-11ea-8d0a-03a8464a1c8b.png)
this image says (in Portuguese Portuagal) that i need a permission from the adminstrator to make changes on the file.

Thank you, dnfanjos

**Comment by dnfanjos** [comment]
UPDATE! It seems to be a ghost file since i cannot open it with winrar

**Comment by dnfanjos** [comment]
nvm i restarted the pc and was able to successfuly delete the file

**Comment by ParthK117** [comment]
Sorry, I hadn't noticed there was an issue until now, I'm glad it's been fixed. This error shows up when you're trying to delete a file that's still downloading (and emuloader is the owner of the file until it's finished downloading so you can't delete it), and if its closed before the download is finished it doesnt get to release the file. Do you know how I can replicate this error?

**Comment by dnfanjos** [comment]
download a rom (psp version of persona 3) restart pc and try deleting the rom (you will know you did it when the pc refuses to delete)

**Comment by ParthK117** [comment]
And what version of emuloader were you using?

**Comment by dnfanjos** [comment]
The most recent version at the date of making this issue (28/6/2020)

**Comment by ParthK117** [comment]
I've added a function that runs when emuloader is started to delete any residual or broken downloads, and it will be available in 1.0.0
